#pragma once
#include<Windows.h>
#include<cstdlib>
#include<ctime>
#include<cstdio>
using namespace std;


//设置光标位置
void Goto_XY(const int x, const int y);
//隐藏光标
void HideCursor();
//产生0~n的随机数
inline int RANDOM(int n) { return rand() % n; }
//设置窗口大小
void SetWindowSize(int cols, int lines);
//设置文本颜色
void SetColor(int colorID);


//亮白色
const int WHITE_COLOR = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY;
//亮红色
const int RED_COLOR = FOREGROUND_RED | FOREGROUND_INTENSITY;
//亮蓝色
const int BLUE_COLOR = FOREGROUND_BLUE | FOREGROUND_INTENSITY;
//亮绿色
const int GREEN_COLOR = FOREGROUND_GREEN | FOREGROUND_INTENSITY;
//亮蓝绿色
const int BLUE_GREEN_COLOR = FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY;
//淡蓝绿色
const int BLUE_LITE_COLOR = FOREGROUND_BLUE | FOREGROUND_GREEN;
//亮黄色
const int YELLOW_COLOR = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY;
//淡黄色
const int YELLOW_LITE_COLOR = FOREGROUND_RED | FOREGROUND_GREEN;
//灰色
const int GRAY_COLOR = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE;
//亮粉色
const int PINK_COLOR = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY;

/* 含背景色 */
const int TITLE_COLOR = BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE;
const int SELECTED_COLOR = BACKGROUND_GREEN | BACKGROUND_BLUE | WHITE_COLOR;
const int THEME_COLOR = BLUE_GREEN_COLOR;
const int GAMENAME_COLOR = FOREGROUND_GREEN;
const int HIGHLIGHT_COLOR = BACKGROUND_GREEN | WHITE_COLOR;
const int PAUSE_COLOR = BACKGROUND_RED | WHITE_COLOR;
const int LOST_COLOR = BACKGROUND_RED | BACKGROUND_INTENSITY | WHITE_COLOR;
const int WIN_COLOR = BACKGROUND_GREEN | BACKGROUND_INTENSITY | WHITE_COLOR;
const int MODE_COLOR = TITLE_COLOR | FOREGROUND_GREEN;